# Generated by Django 3.0.7 on 2020-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
