# Generated by Django 3.0.7 on 2020-06-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_job_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('password', models.CharField(default='', max_length=200, null=True)),
                ('detail', models.TextField(blank=True)),
                ('contact_no', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
