# Generated by Django 3.0.7 on 2020-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
