# Generated by Django 3.0.7 on 2020-06-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Job'),
        ),
    ]
