# Generated by Django 3.0.7 on 2020-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_company_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
