# Generated by Django 3.0.7 on 2020-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employee_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(max_length=200)),
                ('ref_id', models.CharField(max_length=200)),
                ('ref_content', models.CharField(max_length=200)),
            ],
        ),
    ]
