# Generated by Django 3.0.7 on 2020-06-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
