# Generated by Django 3.0.3 on 2020-07-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification_read_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
