# Generated by Django 3.0.3 on 2020-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200702_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
