# Generated by Django 3.0.3 on 2020-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
